#!/usr/bin/env python3
"""
Build script: reads _projects/*.md → writes data/projects.js

Each .md file uses YAML frontmatter for structured data and a Markdown body
for prose content (goals, benefits). Run this script after editing any .md file.

Usage:
    python build.py

Output:
    data/projects.js  (ES module, imported by the website JS)
"""

import json
import os
import sys
from pathlib import Path

try:
    import frontmatter
    import markdown
except ImportError:
    print("ERROR: Missing dependencies. Run: pip install -r requirements.txt")
    sys.exit(1)

PROJECTS_DIR = Path("_projects")
OUTPUT_FILE = Path("data/projects.js")

# Allowed values for validation
VALID_CATEGORIES = {"infrastructure", "domain", "accuracy", "usability"}
VALID_MATURITIES = {"early", "mid", "late", "end", "full"}
VALID_STAGES = {"infra_updates", "data_generation", "fitting", "benchmarking", "release", "community_maintenance"}

md_converter = markdown.Markdown(extensions=["extra"])


def parse_project(path: Path) -> dict:
    """Parse a single project .md file and return a validated dict."""
    post = frontmatter.load(str(path))
    fm = post.metadata
    slug = path.stem

    # Required fields
    required = ["id", "title", "category", "recommended", "summary",
                "fte", "timeline", "metrics", "go_no_go"]
    for field in required:
        if field not in fm:
            print(f"WARNING: {path.name} missing required field '{field}'")

    project_id = fm.get("id", slug)
    if project_id != slug:
        print(f"WARNING: {path.name} has id='{project_id}' but filename is '{slug}' — using filename")
        project_id = slug

    category = fm.get("category", "infrastructure")
    if category not in VALID_CATEGORIES:
        print(f"WARNING: {path.name} has unknown category '{category}'")

    maturity = fm.get("maturity", "early")
    if maturity not in VALID_MATURITIES:
        print(f"WARNING: {path.name} has unknown maturity '{maturity}'")

    stages = fm.get("stages", [])
    for s in stages:
        if s not in VALID_STAGES:
            print(f"WARNING: {path.name} has unknown stage '{s}'")

    fte = fm.get("fte", {})
    fte_normalized = {
        "infrastructure": float(fte.get("infrastructure", 0)),
        "science_code": float(fte.get("science_code", 0)),
        "science_exp": float(fte.get("science_exp", 0)),
        "other": float(fte.get("other", 0)),
    }

    # Convert markdown body to HTML
    md_converter.reset()
    body_html = md_converter.convert(post.content.strip()) if post.content.strip() else ""

    return {
        "id": project_id,
        "title": fm.get("title", project_id),
        "category": category,
        "maturity": maturity,
        "recommended": bool(fm.get("recommended", False)),
        "stages": stages,
        "summary": fm.get("summary", ""),
        "fte": fte_normalized,
        "timeline": fm.get("timeline", []),
        "metrics": fm.get("metrics", []),
        "go_no_go": fm.get("go_no_go", []),
        "dependencies": fm.get("dependencies", []),
        "enables": fm.get("enables", []),
        "body_html": body_html,
    }


def build():
    if not PROJECTS_DIR.exists():
        print(f"ERROR: {PROJECTS_DIR} directory not found")
        sys.exit(1)

    md_files = sorted(PROJECTS_DIR.glob("*.md"))
    if not md_files:
        print(f"ERROR: No .md files found in {PROJECTS_DIR}")
        sys.exit(1)

    projects = []
    for path in md_files:
        try:
            project = parse_project(path)
            projects.append(project)
            print(f"  ✓ {path.name} → {project['id']}")
        except Exception as e:
            print(f"  ✗ {path.name}: {e}")
            sys.exit(1)

    # Validate cross-references
    all_ids = {p["id"] for p in projects}
    for p in projects:
        for dep in p["dependencies"]:
            if dep not in all_ids:
                print(f"WARNING: {p['id']} depends on unknown id '{dep}'")
        for enables in p["enables"]:
            if enables not in all_ids:
                print(f"WARNING: {p['id']} enables unknown id '{enables}'")

    # Write output
    OUTPUT_FILE.parent.mkdir(exist_ok=True)
    projects_json = json.dumps(projects, indent=2, ensure_ascii=False)

    output = f"""// AUTO-GENERATED by build.py — do not edit manually.
// Edit _projects/*.md files instead, then re-run: python build.py

export const PROJECTS = {projects_json};

export const CATEGORIES = {{
  infrastructure: {{ label: "Infrastructure / Fitting Pipeline", color: "#6366f1" }},
  domain:         {{ label: "Domain Expansion",                  color: "#10b981" }},
  accuracy:       {{ label: "Accuracy Improvements",             color: "#f59e0b" }},
  usability:      {{ label: "Usability / Community",             color: "#ec4899" }},
}};

export const STAGE_LABELS = {{
  infra_updates:        "Upfront Infrastructure",
  data_generation:      "Data Generation",
  fitting:              "Fitting",
  benchmarking:         "Benchmarking",
  release:              "Release",
  community_maintenance: "Community & Maintenance",
}};

export const ALL_STAGES = ["infra_updates", "data_generation", "fitting", "benchmarking", "release", "community_maintenance"];

export const MATURITY_COLORS = {{
  early: "#f97316",
  mid:   "#eab308",
  late:  "#22c55e",
  end:   "#94a3b8",
  full:  "#a78bfa",
}};

export const MATURITY_LABELS = {{
  early: "Early Stage",
  mid:   "Mid Stage",
  late:  "Late Stage",
  end:   "End Stage",
  full:  "Full Pipeline",
}};

// Lookup helpers
export const PROJECT_MAP = Object.fromEntries(PROJECTS.map(p => [p.id, p]));
"""

    OUTPUT_FILE.write_text(output, encoding="utf-8")
    print(f"\nWrote {len(projects)} projects to {OUTPUT_FILE}")


if __name__ == "__main__":
    print(f"Building from {PROJECTS_DIR}/*.md...")
    build()
